# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "JinyStudyBox"
description: > # this means to ignore newlines until "email:"
   기억하기 보단 기록으로 남기자

email: jihojhi@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Hyojin'
author: 'Hyojin'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards


  - icon:	github
    url:	https://github.com/jihojhi
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

